## 01 - Mátrixszorzás
Az alábbi mátrixok közül 

\begin{equation}
M_1=\left(\begin{array}{ccc}
3 &6 &3\\
9 &3 &9\\
2 &0 &2
\end{array}\right)\,, 
M_2=\left(\begin{array}{ccc}
7 &9 &6\\
9 &3 &0\\
1 &2 &3
\end{array}\right)\,, 
M_3=\left(\begin{array}{ccc}
3 &2 &6\\
6 &5 &9\\
8 &5 &8
\end{array}\right)\,,
M_4=\left(\begin{array}{ccc}
0 &2 &9\\
6 &5 &4\\
9 &9 &2\end{array}\right)
\end{equation}


ha kettőt megfelelő sorrendben összeszorzunk, akkor eredményül az

\begin{equation}
X=\left(\begin{array}{ccc}
36&   6&  36\\
71&  51&  71\\
112&  81& 112
\end{array}\right)
\end{equation}

mátrixot kapjuk.

* Határozzuk meg, hogy melyik mátrixok azok, amelyek a szorzás tényezőit adják, illetve hogy milyen sorrendben kell a szorzást elvégezni!
* Mely mátrixok invertálhatóak $M_1,\dots,M_4$ közül?

*Segítségül listaformátumban a következő cellából kimásolhatók a mátrixok.*

In [1]:
# A szokásos import
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [42]:
m1=matrix([[3,6,3],
          [9,3,9],
          [2,0,2]])

m2=matrix([[7,9,6],
          [9,3,0],
          [1,2,3]]) 

m3=matrix([[3,2,6],
          [6,5,9],
          [8,5,8]])

m4=matrix([[0,2,9],
          [6,5,4],     # definiálom a mátrixokat
          [9,9,2]])

mx=matrix([[36,6,36],
         [71,51,71],
         [112,81,112]])


for i in [m1,m2,m3,m4]:
    for j in [m1,m2,m3,m4]:  # bepakolom egy listába a mátrixokat és az i, j változót "akasztom" rájuk
        res=i*j     #definiálom a i,j szorzását hogy könnyebben lehessen egyenlőséget tenni köztük
        if (res == mx).all(): # megvizsgálom a műveletek végeredményeinek egyenlőségét az egész mátrixra nézve
            print(i,j) #majd a helyes megoldátst kiiratom és leolvasom hogy melyik mátrixok eredménye az mx-mátrix
                       #figyelve a szorzás sorrendjére.



[[0 2 9]
 [6 5 4]
 [9 9 2]] [[3 6 3]
 [9 3 9]
 [2 0 2]]


In [41]:
m4*m1

matrix([[ 36,   6,  36],
        [ 71,  51,  71],
        [112,  81, 112]])

A ciklus eredményéből kiolvasható, hogy akkor kapjuk meg eredményül a mx mátrixot ha az m4*m1 műveletet végrehajtjuk.

In [32]:
inv(m2)  #inv fv-el invertálom a mátrixokat

matrix([[-0.1       ,  0.16666667,  0.2       ],
        [ 0.3       , -0.16666667, -0.6       ],
        [-0.16666667,  0.05555556,  0.66666667]])

In [33]:
inv(m3)

matrix([[ 0.18518519, -0.51851852,  0.44444444],
        [-0.88888889,  0.88888889, -0.33333333],
        [ 0.37037037, -0.03703704, -0.11111111]])

In [34]:
inv(m4)

matrix([[-0.20155039,  0.59689922, -0.28682171],
        [ 0.18604651, -0.62790698,  0.41860465],
        [ 0.06976744,  0.13953488, -0.09302326]])

In [35]:
inv(m1) # nem invertálható

LinAlgError: Singular matrix