## 03 - Ortogonális mátrixok

Döntsük el, hogy a következő mátrix lehet-e  lehet-e ortonormált bázisok közti áttérés mátrixa, azaz ortogonális mátrix-e?

$$T=\left(\begin{array}{ccc}0.7288991255358142 & -0.4338837391175581 & -0.5295762133276873\\
        -0.3335273011906018 & 0.4504844339512097 & -0.8281445007534446\\
         0.5978842732114963 & 0.7802619276224011 & 0.1836456374361667\\
\end{array}\right)$$

Végezzük el a bázistranszformációt az 1. feladatbeli $M_2$ mátrixon, és ellenőrizzük, hogy a spúrja és determinánsa megváltozott-e!

*Segítségül a mátrixot listaformátumban megadtuk a következő cellában.*

In [2]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [3]:
T=[[ 0.7288991255358142, -0.4338837391175581, -0.5295762133276873],
        [-0.3335273011906018,  0.4504844339512097, -0.8281445007534446],
        [ 0.5978842732114963,  0.7802619276224011,  0.1836456374361667]]

mt=matrix(T) #definiálom a mátrixomat

inv(mt)/mt.T  #az osztással megvizsgálom hogy az invertált mx megegyezik-e a transzponáltal,
               #hiszen egy mátrix akkor ortogonális ha az inverze és a Transzponáltja megegyezik.
    #Esetünkben a mátrix ortogonális

matrix([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])

In [4]:
mt.T

matrix([[ 0.72889913, -0.3335273 ,  0.59788427],
        [-0.43388374,  0.45048443,  0.78026193],
        [-0.52957621, -0.8281445 ,  0.18364564]])

In [5]:
inv(mt)

matrix([[ 0.72889913, -0.3335273 ,  0.59788427],
        [-0.43388374,  0.45048443,  0.78026193],
        [-0.52957621, -0.8281445 ,  0.18364564]])

In [8]:

b=matrix([[7,9,6],
          [9,3,0],
          [1,2,3]]) 

x=mt*b*inv(mt)

trace(b)/trace(x) #ugyanilyen módszerrel megvizsgálom, hogy a mátrixok trace-jei megyegyeznek-e, azt tapasztaljuk, hogy igen.

1.0000000000000002

In [7]:
det(b)/det(x) # a determinánsa azonban megegyezik

1.0000000000000009